export const METHODTS = {
    CONNECTION: 'CONNECTION',
    CREATE_MESSAGE: 'CREATE_MESSAGE',
    FIND_ALL_MESSAGE: 'FIND_ALL_MESSAGE',
    UPDATE_MESSAGE: 'UPDATE_MESSAGE',
    REMOVE_MESSAGE: 'REMOVE_MESSAGE',

    JOIN_ROOM: 'JOIN_ROOM',
    SEND_OFFER: 'SEND_OFFER',
    SEND_ANSWER: 'SEND_ANSWER',
    SEND_ICE_CANDIDATE: 'SEND_ICE_CANDIDATE',
    disconnect: 'disconnect',

    RECEIVE_CLIENT_JOINED: 'RECEIVE_CLIENT_JOINED',
    RECEIVE_OFFER: 'RECEIVE_OFFER',
    RECEIVE_ANSWER: 'RECEIVE_ANSWER',
    RECEIVE_ICE_CANDIDATE: 'RECEIVE_ICE_CANDIDATE',
    RECEIVE_DISONECT: 'RECEIVE_DISONECT',

    CREATE_WEBRTC_TRANSPORT: 'CREATE_WEBRTC_TRANSPORT',
}
