export const METHODTS = {
    CONNECTION: 'CONNECTION',
    JOIN_ROOM: 'JOIN_ROOM',
    CREATE_MESSAGE: 'CREATE_MESSAGE',
    FIND_ALL_MESSAGE: 'FIND_ALL_MESSAGE',
    UPDATE_MESSAGE: 'UPDATE_MESSAGE',
    REMOVE_MESSAGE: 'REMOVE_MESSAGE',
    USER_CONNECTED: 'USER_CONNECTED',
}
